name: Test - Build and deploy
on:
  workflow_dispatch:

env:  
  SRC_PATH: ./src
  LOCATION: "westeurope"
  RG_NAME: "cnawebappui-rg"
  IMAGE_NAME: 'pierrcacr.azurecr.io/cnawebappui'
  IMAGE_VERSION: 'v.0.5.2'


jobs:                                     
  build:
    runs-on: ubuntu-latest                
    
    steps:
    - name: "Checkout the code"
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Build and Test the App
      run: |
        dotnet restore ${{env.SRC_PATH}}
        dotnet build ${{env.SRC_PATH}} --configuration Release --no-restore    
        dotnet test ${{env.SRC_PATH}} --no-restore --verbosity normal
        dotnet publish ${{env.SRC_PATH}}/WebAppUI/ -o ${{env.SRC_PATH}}/WebAppUI/publish

    - name: Build Image
      run: |
        docker build --pull -t $webappnameinitcode -f  dockerfilepath slnpath

    - name: Check
      run: |
        ls
        docker image ls