name: Test - Build and deploy
on:
  workflow_dispatch:

env:
  LOCATION: "westeurope"  
  RG_NAME: "cnawebappui-rg"
  ACR_NAME: "cnawebappuiacr"
  ACR_SKU: "Standard"

  
  DOTNET_VERSION: 3.1.x
  SRC_PATH: ./src 


jobs:                                     
  build-Test-Push-Image:
    runs-on: ubuntu-20.04

    steps:
    - name: "Checkout the code"
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: Azure/login@v1
      with:        
          creds: ${{secrets.AZURE_CREDENTIALS}} 

    - name: Get Key ACR
      run: |
        key=`az acr credential show --resource-group ${{ env.RG_NAME }} --name ${{ env.ACR_NAME}} --query passwords[0].value --output tsv`
        echo "::set-output name=content::$key"
      id: var_acrkey

    - name : test
      run: |
        echo "${{ steps.var_acrkey.outputs.content }}"