name: Test - Build and deploy
on:
  workflow_dispatch:

env:
  LOCATION: "westeurope"  
  RG_NAME: "cnawebappui-rg"
  ACR_NAME: "cnawebappuiacr"
  ACR_SKU: "Standard"

  
  DOTNET_VERSION: 3.1.x
  SRC_PATH: ./src 


jobs:                                     
  build-Test-Push-Image:
    runs-on: ubuntu-20.04

    steps:
    - name: "Checkout the code"
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: Azure/login@v1
      with:        
          creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy infra (RG & ACR)
      run: |
        az deployment sub create \
          --location ${{ env.LOCATION}} \
          --template-file ./Bicep/mainACR.bicep \
          --parameters 'RgSiteName=${{ env.RG_NAME }}' 'ACRName=${{ env.ACR_NAME }}' 'ACRSku=${{ env.ACR_SKU }}'

    