name: Test - Build and deploy
on:
  workflow_dispatch:

env:
  LOCATION: "westeurope"  
  RG_NAME: "cnawebappui-rg"
  ACR_NAME: "cnawebappuiacr"
  ACR_SKU: "Standard"
  IMAGE_NAME: "WoodGrove"

  
  DOTNET_VERSION: 3.1.x
  SRC_PATH: ./src 


jobs:                                     
  build-Test-Push-Image:
    runs-on: ubuntu-20.04

    steps:
    - name: "Checkout the code"
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: Azure/login@v1
      with:        
          creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy infra (RG & ACR)
      run: |
        az deployment sub create \
          --location ${{ env.LOCATION}} \
          --template-file ./Bicep/mainACR.bicep \
          --parameters 'RgSiteName=${{ env.RG_NAME }}' 'ACRName=${{ env.ACR_NAME }}' 'ACRSku=${{ env.ACR_SKU }}'

    - name: Build and Test the App
      run: |
        #dotnet restore ${{env.SRC_PATH}}
        #dotnet build ${{env.SRC_PATH}} --configuration Release --no-restore    
        #dotnet test ${{env.SRC_PATH}} --no-restore --verbosity normal
        #dotnet publish ${{env.SRC_PATH}}/WebAppUI/ -o ${{env.SRC_PATH}}/WebAppUI/publish
        dotnet publish --self-contained true -r linux-x64 -c release ./src/WebAppUI/CnAppForAzureDev.csproj -o ./Build/publish   

    - name: Get Key ACR
      run: |
        key=`az acr credential show --resource-group ${{ env.RG_NAME }} --name ${{ env.ACR_NAME}} --query passwords[0].value --output tsv`
        echo "::set-output name=content::$key"
      id: var_acrkey

    - name : test
      run: |
        echo "${{ steps.var_acrkey.outputs.content }}"

    - name: Connexion à Azure Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_NAME }}
        password: "${{ steps.var_acrkey.outputs.content }}"

    - name: Extraire les métadonnées docker
      id: meta
      uses: docker/metadata-action@v3.5.0
      with:
        images: ${{ env.ACR_NAME }}.azurecr.io/${{ IMAGE_NAME }} 
        tags: |
         type=semver,pattern={{version}},value=1.0.0


    - name: Construire et pousser image Docker
      uses: docker/build-push-action@v2.7.0
      with:         
          context: ./
          file: ./Build/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
