name: Test - Build and deploy
on:
  workflow_dispatch:

env:  
  SRC_PATH: ./src
  LOCATION: "westeurope"
  DOTNET_VERSION: 3.1.x
  RG_NAME: "cnawebappui-rg"
  ACR_NAME: "cnawebappuiacr"
  ACR_SKU: "Standard"
  APP_PLAN_NAME: "cnawebappui-plan"
  SKU_PLAN: "S1"


jobs:                                     
  build-Test-Push-Image:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout the code"
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: Azure/login@v1
      with:        
          creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy infra (RG & ACR)
      run: |
        az deployment sub create \
          --location ${{ env.LOCATION}} \
          --template-file ./Bicep/mainACR.bicep \
          --parameters 'RgSiteName=${{ env.RG_NAME }}' 'ACRName=${{ env.ACR_NAME }}' 'ACRSku=${{ env.ACR_SKU }}'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Build and Test the App
      run: |
        #dotnet restore ${{env.SRC_PATH}}
        #dotnet build ${{env.SRC_PATH}} --configuration Release --no-restore    
        #dotnet test ${{env.SRC_PATH}} --no-restore --verbosity normal
        #dotnet publish ${{env.SRC_PATH}}/WebAppUI/ -o ${{env.SRC_PATH}}/WebAppUI/publish
        dotnet publish --self-contained true -r linux-x64 -c release ./src/WebAppUI/CnAppForAzureDev.csproj -o ./Build/publish

    - name: Connexion à Azure Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: cnawebappuiacr.azurecr.io
        username: cnawebappuiacr
        password: GqYkjRgbRmY8WpNOSGs1sI6X4+SfLCxV

    #- name: Extraire les métadonnées docker
    #  id: meta
    #  uses: docker/metadata-action@v3.5.0
    #  with:
    #    images: cnawebappuiacr.azurecr.io/WoodGrove 
    #    tags: |
    #     type=semver,pattern={{version}},value=1.0.0

    - name: Construire image Docker
      run: |
        docker build -f ./Build/Dockerfile . -t test      