name: Test ~> Build ~> Push
on:
  push:
    paths:
      - 'src/**'
env:
  # Resource Group et Azure Container Registry 
  LOCATION: "westeurope"  
  RG_NAME: "cnawebappui-rg"
  ACR_NAME: "cnawebappuiacr"
  ACR_SKU: "Standard"
  IMAGE_NAME: "woodgrove"
  IMAGE_VERSION: "1.0.5"

jobs:                                     
  build-Test-Push-Image:
    runs-on: ubuntu-20.04

    steps:
    - name: "Checkout the code"
      uses: actions/checkout@v2

    - name: Build and Test the App
      run: |
        dotnet restore ./src/
        dotnet build ./src/ --configuration Release --no-restore    
        dotnet test ./src/ --no-restore --verbosity normal      
        dotnet publish --self-contained true -r linux-x64 -c release ./src/WebAppUI/CnAppForAzureDev.csproj -o ./Build/publish

    - name: Login to Azure
      uses: Azure/login@v1
      with:        
          creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Login Azure Container Registry
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    - name: Extraire les métadonnées docker
      id: meta
      uses: docker/metadata-action@v3.5.0
      with:
        images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }} 
        tags: |
         type=semver,pattern={{version}},value=${{ env.IMAGE_VERSION }}

    - name: Construire et pousser image Docker
      uses: docker/build-push-action@v2.7.0
      with:         
          context: ./
          file: ./Build/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}